include vague.conf

#font#
font_family JetBrainsMono Nerd Font
font_size 20
enable_lgatures yes
italic_font yes
bold_font yes

#cursor#
cursor_shape beam
cursor_shape_unfocused hollow
cursor_trail 1

#mouse
mouse_hide_wait 2.0

url_color #0087bd
url_style curly
open_url_with default
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto stfp ssh
detect_urls yes
copy_on_select yes

#terminal bell
enable_audio_bell no
confirm_os_window_close 0
#tabs
tab_bar_edge top
tab_bar_style fade
tab_bar_min_tabs 2
tab_separator "|"

#margin
window_padding_width 6

##color scheme##
background_opacity 0.9
background_blur 1

background_image none


#foreground #d7c0a3
#background #292929

#base color
#color0 #292929
#color1 #b77b50
#color2 #a88c65
#color3 #d7b07a
#color4 #8c7c6a
#color5 #b08fa0
#color6 #9bb1a0
#color7 #d7c0a3

#bright variantes
#color8 #44403a
#color9 #d67e5d
#color10 #b4a77b
#color11 #e0c08a
#color12 #a89d8f
#color13 #c6a3b0
#color14 #a0b0a0
#color15 #f0e3c8


